#!/usr/local/bin/php
<?php
require_once '../lib/meekrodb.2.3.class.php';
require_once '../lib/Combinatorics.php';

DB::$user = 'root';
DB::$password = 'root';
DB::$dbName = 'bixibeats';
DB::$host = '127.0.0.1'; //defaults to localhost if omitted
DB::$port = '33306'; // defaults to 3306 if omitted
DB::$encoding = 'utf8'; // defaults to latin1 if omitted

$stations = DB::queryOneColumn('id', "SELECT * FROM stations");

$combinatorics = new Math_Combinatorics;

$ods = $combinatorics->combinations( $stations, 2 );

foreach ($ods as $od) {
	$first = array_shift($od);
	$last = array_pop($od);
	DB::insert('routes',array(
		'start_station_id' => $first,
		'end_station_id' => $last
	));
	DB::insert('routes',array(
		'start_station_id' => $last,
		'end_station_id' => $first
	));
}

echo "Done!";