#!/usr/local/bin/php
<?php
require_once '../lib/meekrodb.2.3.class.php';

$mb_token = 'pk.eyJ1IjoiYnJvY2hlYWZvaW4iLCJhIjoiY2loaWljbjNqMDR5MXRoajd3dmpmYmFrbiJ9.tbocSVZpED7Bu18y3jzB3g';

DB::$user = 'root';
DB::$password = 'root';
DB::$dbName = 'bixibeats';
DB::$host = '127.0.0.1'; //defaults to localhost if omitted
DB::$port = '33306'; // defaults to 3306 if omitted
DB::$encoding = 'utf8'; // defaults to latin1 if omitted

$routes = DB::query("SELECT o.longitude as o_longitude, o.latitude as o_latitude, o.nom as o_name , d.longitude as d_longitude, d.latitude as d_latitude, d.nom as d_name FROM routes r inner join stations o on r.start_station_id = o.id inner join stations d on r.end_station_id = d.id order by rand() limit 60");

$output = array(
	'type' => 'FeatureCollection',
	'crs' => array(
		"type" => "name",
		"properties" => array(
			"name" => "urn:ogc:def:crs:OGC:1.3:CRS84"
		)
	),
	'features' => array()
);

foreach ($routes as $route) {
	$o = remove_zeros( $route['o_longitude'] ) . ',' . remove_zeros( $route['o_latitude']);
	$d = remove_zeros( $route['d_longitude'] ) . ',' . remove_zeros( $route['d_latitude']);
	$url = 'https://api.mapbox.com/v4/directions/mapbox.cycling/'. $o .';' . $d .'.json?alternatives=false&instructions=text&geometry=geojson&steps=false&access_token=' . $mb_token;
	$result = json_decode(file_get_contents($url));
	$directions = $result->routes[0];
	$output['features'][] = array(
		'type' => 'Feature',
		'properties' => array(
			'start' => $route['o_name'],
			'end' => $route['d_name']
		),
		'geometry' => $directions->geometry
	);
}

echo json_encode( $output );

function remove_zeros( $string ) {
	return rtrim( $string, '0');
}