#!/usr/local/bin/php
<?php
require_once '../lib/meekrodb.2.3.class.php';

DB::$user = 'root';
DB::$password = 'root';
DB::$dbName = 'bixibeats';
DB::$host = '127.0.0.1'; //defaults to localhost if omitted
DB::$port = '33306'; // defaults to 3306 if omitted
DB::$encoding = 'utf8'; // defaults to latin1 if omitted

$fp = fopen('../data/rides.json','w');
fwrite($fp,"[");

$rides = DB::query( "
SELECT
id,
timestampdiff(second,'2015-08-06 04:00',start_time) as start,
route_id,
(duration * 60) as duration,
lcase(concat( gender, language )) as member_type
 FROM rides order by start_time asc
" );

foreach ( $rides as $index => $ride ) {
	if (empty($ride['member_type'])) $ride['member_type'] ='g';
	$ride_output = array(
		'id' => (int) $ride['id'],
		'route' => (int) $ride['route_id'],
		'start' => (int) $ride['start'],
		'duration' => (int) $ride['duration'],
		'type' => $ride['member_type'],
	);

	fwrite($fp,json_encode($ride_output));
	// Except for last route
	if ( ($index + 1) < count($rides) ) {
		fwrite($fp,',');
	}
}

fwrite($fp,"]");

echo "Rides JSON generated.\n";
