#!/usr/local/bin/php
<?php
require_once '../lib/meekrodb.2.3.class.php';

DB::$user = 'root';
DB::$password = 'root';
DB::$dbName = 'bixibeats';
DB::$host = '127.0.0.1'; //defaults to localhost if omitted
DB::$port = '33306'; // defaults to 3306 if omitted
DB::$encoding = 'utf8'; // defaults to latin1 if omitted

$fp = fopen('../data/stations.json','w');

$output = array();

$stations = DB::query( "SELECT * FROM stations" );

foreach ( $stations as $station ) {
	$output[]  = array(
		remove_zeros( $station['latitude']),
		remove_zeros( $station['longitude'])
	);
}

fwrite( $fp, json_encode($output));

echo "Stations JSON generated.\n";

function remove_zeros( $string ) {
	return (float) rtrim( $string, '0');
}